myshop/cart/urls.py
from django.urls import re_path 
from . import views


urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include
from django.urls import re_path 

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'about_us/', include(('about_us.urls', 'about_us'), namespace='about_us')),
    re_path(r'^orders/', include(('orders.urls', 'orders'), namespace='orders')),
    re_path(r'^cart/', include(('cart.urls', "cart"), namespace='cart')),
    re_path(r'^', include(('shop.urls', 'shop'), namespace='shop')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from . import views
from django.urls import re_path 


urlpatterns = [
    re_path(r'^create/$', views.order_create, name='order_create'),
    re_path(r'^admin/order/(?P<order_id>\d+)/$', views.admin_order_detail, name='admin_order_detail'),
]

myshop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 3)]


class CartAddProductForm(forms.Form):
    quantity = 1
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=1,
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

myshop/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %} 
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br> 
    <center><div id="main" class="product-list" style="margin-left: auto; margin-right: auto;">
        <div class="product-grid">
            {% for product in cart %}
            <div class="item" style="padding-bottom: 40px;">

                {% if product.available == True %}
                <a href="{{ product.get_absolute_url }}" class="product-link">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" 
                        alt="{{ product.name }}" 
                        class="product-image"
                        width="70%" height="70%" style="max-width: 500px; max-height: 700px;">
                </a>
                <div class="text-center">
                    <a href="{{ product.get_absolute_url }}" style="padding-top: 50%;" class="product-title">
                        {{ product.name }}
                    </a>
                    
                    <div class="product-price">
                        {{ product.price }} ₽
                    </div>
                    
                </div>
                {% else %}
                <div class="image-container">
                    <a>
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" 
                            alt="{{ product.name }}" 
                            class="product-image"
                            width="70%" height="70%" style="max-width: 500px; max-height: 700px;">
                        <div class="sold-out-tag">Распроданный</div>
                    </a>
                    <div class="product-details text-center">
                        <a class="product-title">{{ product.name }}</a>
                        <div class="product-price">{{ product.price }} ₽</div>
                    </div>
                </div>
                {% endif %}
            </div>
        {% endfor %}
        </div>
    </div></center> 
    <form action="{% url 'orders:order_create' %}">
        <center><button type="submit" class="btn-cart">Оформить заказ</button></center>
    </form>
{% endblock %}